Enhance Primer when WooCommerce is active
godaddy/wp-primer-theme pull request #134
Opened 2016-11-16 21:39 UTC by EvanHerman

The follow patch makes enhancements to Primer when WooCommerce is active.

1) 404 Template: A new template is now loaded in place of the default 404 template.

**Example:**
![WooCommerce 404 Example](https://cldup.com/oVqjkumcZq.png)

2016-12-06 18:47 UTC, fjarrett commented
@EvanHerman Any reason behind using an underscore in the template part named `404_woocommerce.php`? It breaks the convention used on all the other partials.

2016-12-06 18:53 UTC, EvanHerman commented
@fjarrett No, I just mis-named the template file. I went back and updated it to match the naming convention.

2016-12-12 16:42 UTC, fjarrett commented on inc/helpers.php
> +	function get_the_widget( $widget, $instance = '', $args = '' ) {
@EvanHerman This global func will need to be prefixed: `primer_get_the_widget()`

2016-12-12 16:43 UTC, fjarrett commented on inc/helpers.php
> +function primer_generate_nav_menu_item( $title, $url, $order, $parent = 0, $classes = array() ) {
@EvanHerman I don't see this function being used anywhere in the theme. Do we still need it?

2016-12-12 16:47 UTC, EvanHerman commented on inc/helpers.php
> +function primer_generate_nav_menu_item( $title, $url, $order, $parent = 0, $classes = array() ) {
@fjarrett This was an oversight. In the original implementation this was being used, but when I refactored the way the menu was being generated this was no longer necessary.

2016-12-16 16:26 UTC, fjarrett commented on inc/compat/woocommerce.php
> +	return $original_template;
@EvanHerman One-liners FTW

```php
return is_404() ? get_stylesheet_directory() . '/templates/parts/404-woocommerce.php' : $original_template;
```

2016-12-16 16:26 UTC, fjarrett commented on inc/compat/woocommerce.php
> + *
@EvanHerman `@filter template_include `

2016-12-16 16:30 UTC, fjarrett commented on inc/compat/woocommerce.php
> +
@EvanHerman Should we make the default values for `$per_page` and `$columns` filterable?

2016-12-16 16:31 UTC, frankiejarrett commented on templates/parts/404-woocommerce.php
> +					<?php echo do_shortcode( '[best_selling_products per_page="4" columns="4"]' ); ?>
@EvanHerman Should we make a wrapper for this like we did with `primer_wc_promoted_products()`?

2016-12-16 16:34 UTC, fjarrett commented on inc/compat/woocommerce.php
> +
@EvanHerman Also, I think they should be ints instead of strings, and we should with sanitize with `absint` before using them.

2016-12-16 16:35 UTC, fjarrett commented on inc/compat/woocommerce.php
> +	if ( ! apply_filters( 'primer_wc_cart_menu', true ) ) {
@EvanHerman Let's add a docblock for this filter.

2016-12-16 16:36 UTC, fjarrett commented on inc/compat/woocommerce.php
> +	if ( ! apply_filters( 'primer_wc_cart_menu', true ) ) {
@EvanHerman And rename to be `primer_wc_show_cart_menu`.

2016-12-16 16:37 UTC, fjarrett commented on inc/compat/woocommerce.php
> +	$cart_total      = is_customize_preview() ? '0.00' : $woocommerce->cart->get_cart_total();
@EvanHerman I don't think the `'0.00'` format will work with every currency.

2016-12-16 16:43 UTC, fjarrett commented on inc/compat/woocommerce.php
> +		'<li id="woocommerce-cart-menu-item" class="menu-item-has-children menu-item menu-item-type-nav_menu_item menu-item-object-cart woocommerce-cart-menu-item"><a><span class="cart-preview-total"><span
@EvanHerman I'm worried here about menu item classes being hardcoded. Any ideas?

2016-12-16 16:47 UTC, fjarrett commented on .dev/sass/compat/woocommerce.scss
> +#woocommerce-cart-menu-item {
@EvanHerman I'm not sure about venturing into the `woocommerce` namespace. What do you think?

2017-01-09 23:44 UTC, fjarrett commented on inc/compat/woocommerce.php
> +	return $original_template;
@EvanHerman One-liners FTW

```php
return is_404() ? get_stylesheet_directory() . '/templates/parts/404-woocommerce.php' : $original_template;
```

2017-01-09 23:44 UTC, fjarrett commented on inc/compat/woocommerce.php
> + *
@EvanHerman `@filter template_include `

2017-01-09 23:53 UTC, frankiejarrett requested changes
Left some comments inline.

2017-01-10 18:12 UTC, merged