Add function_exists() checks for has_header_video. Fix PHPCS warning.
godaddy/wp-primer-theme pull request #199
Opened 2017-04-19 21:13 UTC by EvanHerman

Resolves #195 

In the 1.7.0 release checking that the function `has_header_video` is available before using it was overlooked. This PR adds `function_exists()` checks for `has_header_video` where necessary.

Additionally a minor PHPCS error was resolved (associative arrays on individual lines), which was introduced with the latest release of PHPCS.

2017-04-20 15:55 UTC, frankiejarrett requested changes

2017-04-20 15:55 UTC, fjarrett commented on functions.php
> +	$nav_dependencies = ( is_front_page() && ( function_exists( 'has_header_video' ) && has_header_video() ) ) ? array( 'jquery', 'wp-custom-header' ) : array( 'jquery' );
The last two conditions don't have to be grouped, when the second one fails the third won't be attempted.

```php
is_front_page() && function_exists( 'has_header_video' ) && has_header_video()
```

2017-05-23 21:13 UTC, fjarrett commented on functions.php
> +		);
@EvanHerman I find this expanded view less readable, just me?

2017-05-23 21:14 UTC, fjarrett commented on functions.php
> +		);
Is this change within the scope of the PR?

2017-05-23 21:34 UTC, EvanHerman commented on functions.php
> +		);
@fjarrett No, you are correct. This is more difficult to read. During the changes in this PR the new version of the WordPress coding standards was released, and I cam across this change. As per your other comment (on the PR for [Issue #200](https://github.com/godaddy/wp-primer-theme/pull/200)) you are correct. I've gone ahead and reverted this change to remain in scope of the PR.

2017-05-23 21:44 UTC, merged